name: "Get Site Url"
description: "generates the site url based on wp-env"
inputs:
  domain:
    description: "the root domain"
    required: true
  wp-env:
    description: "dev, staging, production"
    required: true
  outputs:
    site-url:
    description: "The site url"
    value: ${{ steps.site-url-generator.outputs.site-url }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: site-url-generator
     run: get-site-url.sh ${{ inputs.domain }} ${{ inputs.wp-env }} >> $GITHUB_OUTPUT
      shell: bash
