name: "Default Deploy"
description: "Builds and Deploys to specified environment"
inputs:
  wp-env:
    required: true
    description: ""
  theme:
    description: theme directory
    required: true
  site_url:
    required: true
    description: ""
  acf_licence_key:
    required: true
    description: ""
  ac_token:
    required: true
    description: ""
  yoast_seo_token:
    required: true
    description: ""
  dev_only_plugins:
    required: true
    description: ""
  ssh-user:
    description: "SSH user to use"
    required: true
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: "22"
  ssh-key:
    description: "SSH key to add"
    required: true
  db_name:
    required: true
    description: ""
  db_user:
    required: true
    description: ""
  db_password:
    required: true
    description: ""
  db_prefix:
    required: true
    description: ""
  wp_cache_key_salt:
    required: true
    description: ""
  wp_redis_database:
    required: true
    description: ""
  destination-path:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    - name: Checkout and Verify Branch is up to date
      uses: atticusseven/.github/actions/checkout-and-verify@main

    - name: Compile, Minify and Combine
      uses: atticusseven/.github/actions/compile-minify-combine@main
      with:
        theme_dir: html/content/themes/${{ inputs.theme }}

    - name: Install Composer Dependencies
      uses: atticusseven/.github/actions/install-composer-dependencies@main
      with:
        site_url: ${{ inputs.site_url }}
        acf_licence_key: ${{ inputs.acf_licence_key }}
        ac_token: ${{ inputs.ac_token }}
        yoast_seo_token: ${{ inputs.yoast_seo_token }}
        env: ${{ inputs.wp-env }}
        dev_only_plugins: ${{ inputs.dev_only_plugins }}

    - name: Add SSH Key to this runner
      uses: atticusseven/.github/actions/add-ssh-key@main
      with:
        ssh-user: ${{ inputs.ssh-user }}
        ssh-port: ${{ inputs.ssh-port }}
        ssh-host: ${{ inputs.ssh-host }}
        ssh-key: ${{ inputs.ssh-key }}

    - name: Create .env from template.env
      uses: atticusseven/.github/actions/setup-env@main
      with:
        db_name: ${{ inputs.db_name }}
        db_user: ${{ inputs.db_user }}
        db_password: ${{ inputs.db_password }}
        db_prefix: ${{ inputs.db_prefix }}
        wp_cache_key_salt: ${{ inputs.wp_cache_key_salt }}
        wp_redis_database: ${{ inputs.wp_redis_database }}
        #network_ip:

    - name: RSync to the Server
      uses: atticusseven/.github/actions/deploy-via-rsync@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: Install Premium Plugins
      uses: atticusseven/.github/actions/install-premium-plugins@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: WP Cleanup
      uses: atticusseven/.github/actions/wp-cleanup@main
      with:
        destination-path: ${{ inputs.destination-path }}

    - name: Make Live
      uses: atticusseven/.github/actions/make-live@main
      with:
        destination-path: ${{ inputs.destination-path }}
        env: ${{ inputs.wp-env }}
