name: "Manage Plugins"
description: "installs, activates, updates, deactivates and removes plugins"
inputs:
  plugins_json_file: # id of input
    description: "The Plugins Json File"
    required: true
    default: "plugins.json"
  destination-path:
    description: "Destination path on the target server"
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: manage-plugins.sh ${{github.workspace}}/${{ inputs.plugins_json_file }} ${{inputs.destination-path}}
      #- run: test-wp-ssh.sh ${{inputs.destination-path}}
      shell: bash
