name: "Manage Plugins"
description: "installs, activates, updates, deactivates and removes plugins"
inputs:
  plugins_json_file: # id of input
    description: "The Plugins Json File"
    required: true
    default: "plugins.json"
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: "22"
  ssh-user:
    description: "SSH user to connect"
    required: true
  destination-path:
    description: "Destination path on the target server"
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    #- run: manage-plugins.sh ${{github.workspace}}/${{ inputs.plugins_json_file }} ${{inputs.ssh-user}} ${{inputs.ssh-host}} ${{inputs.destination-path}}
    #- run: test-wp-ssh.sh ${{github.workspace}}/${{ inputs.plugins_json_file }} ${{inputs.ssh-user}} ${{inputs.ssh-host}} ${{inputs.destination-path}}
    #- run: wp plugin list --skip-plugins --skip-themes --ssh=forge@159.65.24.66:/mnt/falo/sites/dev/dev.findalondonoffice.co.uk/html/wp
    - run: ls -la ~/.ssh
      shell: bash
