name: "WP Clean Up"
description: "Adds our private SSH key to the workflow runner so that it can access the remote server"
inputs:
  destination-path:
    description: "Destination path on the target server"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        wp package install wp-media/wp-rocket-cli:trunk
        wp cache flush --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}/path=html/wp
        wp rewrite flush --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}/path=html/wp
        wp rocket clean --confirm --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}/path=html/wp
      shell: bash
