name: "WP Clean Up"
description: "Flushes the object cache, page cache and rewrites/permalinks"
inputs:
  destination-path:
    description: "Destination path on the target server"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        wp package install wp-media/wp-rocket-cli:trunk
        wp cache flush --skip-plugins --skip-themes --ssh=server:${{ inputs.destination-path }}/html/wp
        wp rewrite flush --ssh=server:${{ inputs.destination-path }}/html/wp
        wp rocket clean --confirm --ssh=server:${{ inputs.destination-path }}/html/wp
      shell: bash
