name: "Deploy via Rsync"
description: ""
inputs:
  destination-path:
    description: "Destination path to copy files"
    required: true
  conf_dir:
    description: Path to the conf dir
    required: true
    default: conf

runs:
  using: "composite"
  steps:
    - name: Switch on maintenance mode
      run: |
        ssh server 'mv ${{inputs.destination-path}}/${{inputs.conf_dir}}/.env ${{inputs.destination-path}}/${{inputs.conf_dir}}/old.env'
        ssh server 'sed -e "s|A7_MAINTENANCE=\"off\"|A7_MAINTENANCE=\"on\"|" ${{inputs.destination-path}}/${{inputs.conf_dir}}/old.env > ${{inputs.destination-path}}/${{inputs.conf_dir}}/.env'
      shell: bash
    - name: Rsync to the remote
      run: rsync -avPC --no-perms --delete-after  --no-perms --exclude-from='${{github.workspace}}/exclude.txt' . server:${{inputs.destination-path}}
      shell: bash
