name: "Deploy via Rsync"
description: ""
inputs:
  destination-path:
    description: "Destination path to copy files"
    required: true

runs:
  using: "composite"
  steps:
    - name: Rsync to the remote
      run: rsync -avPC --no-perms --delete-after  --no-perms --exclude-from='${{github.workspace}}/exclude.txt' . server:${{inputs.destination-path}}
      shell: bash
