name: Synchronise Development

on: workflow_dispatch

jobs:
  sync_remote:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-key@main
        name: Add SSH Key to this runner
        with:
          ssh-port: ${{vars.SSH_PORT}}
          ssh-host: ${{vars.SSH_HOST}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/synchronise-remote@main
        name: Synchronise remote from Production to Staging
        with:
          ssh-port: ${{vars.SSH_PORT}}
          ssh-host: ${{vars.SSH_HOST}}
          ssh-user: ${{vars.SSH_USER}}
          destination-path: ~/sync_live_to_dev.sh

