name: Set Up
description: Installs and configure any packages required for deployment
inputs:
  root_dir:
    description: location of the root directory
    required: true
    default: html
  site_url: # id of input
    description: the site url
    required: true

runs:
  using: composite
  steps:
    - uses: chrisdickinson/setup-yq@latest
    # - name: Install Node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18
    # - name: Install PostCSS, PostCSS CLI and Autoprefixer
    #   run: npm i -D --global postcss postcss-cli autoprefixer
    #   shell: bash
    # - name: Install json (npm package)
    #   run: npm install -g json
    #   shell: bash
    # - name: Install jq (for bash)
    #   run: sudo apt-get install jq
    #   shell: bash
    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        wp --info
        touch ${{github.workspace}}/${{inputs.root_dir}}/wp-cli.yml
        ls -la ${{ github.workspace }}/${{inputs.root_dir}}
      shell: bash
    - name: Set up wp-cli.yml
      run: |
        yq e '.url = "${{inputs.site_url}}"' -i ${{github.workspace}}/${{inputs.root_dir}}/wp-cli.yml; yq e '.path = "wp"' -i ${{github.workspace}}/${{inputs.root_dir}}/wp-cli.yml
        cat ${{github.workspace}}/${{inputs.root_dir}}/wp-cli.yml
      shell: bash
