name: "Parse Json"
description: "filter json array"
inputs:
  plugins_json_file: # id of input
    description: "The Plugins Json File"
    required: true
    default: "plugins.json"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: parse_json.sh ${{github.workspace}}/${{ inputs.plugins_json_file }}
      shell: bash
